### ISSUE TITLE
Missing .unitypackage for each release

### ISSUE THREAD

**Issue by h0ds** [getsentry/sentry-unity-lite#10]
Your README says `The Releases page include a .unitypackage which you can simply drag and drop into your project.`.

But you're missing them for every release other than the initial one.

Could this be addressed? Thanks!

**Comment by bruno-garcia** [comment]
Fixed: https://github.com/getsentry/sentry-unity-lite/commit/2be54328bd36bc5414efec92606907983100f8a1
