### ISSUE TITLE
Unclear how to pass in user_id/email address

### ISSUE THREAD

**Issue by michaeleconomy** [getsentry/sentry-unity-lite#3]
can you guys like document this? or remove the misleading code?

**Comment by bruno-garcia** [comment]
You mean this?

Docs are here: https://docs.sentry.io/enriching-error-data/scopes/?platform=csharp#configuring-the-scope

<img width="776" alt="image" src="https://user-images.githubusercontent.com/1633368/83783934-4dc34180-a65e-11ea-8138-447a39768b0c.png">

**Comment by bruno-garcia** [comment]
This is possible on the current Sentry SDK for Unity developed in this repo: https://github.com/getsentry/sentry-unity
Please follow this documentation here: https://docs.sentry.io/platforms/unity/enriching-events/identify-user/

We're not adding features to sentry-unity-lite so closing this.
