### ISSUE TITLE
Support for synchronous sending operation.

### ISSUE THREAD

**Issue by uskey512** [getsentry/sentry-unity-lite#5]
In the current SDK, `SentrySdk.ContinueSendingEvent` is completely hidden, and some use cases (e.g., sending a log to Sentry immediately after a time-consuming process) do not work correctly.

In order to solve this problem, we need to either implement a method that performs ContinueSendingEvent synchronously, or return the Coroutine that is being sent asynchronously internally from a public method so that SDK users can refer to the status of the process.

**Comment by bruno-garcia** [comment]
Thanks for addressing this. Please note the package details changed so it's grouped differently on UPM.
![image](https://user-images.githubusercontent.com/1633368/103594678-5e26ed80-4ec7-11eb-8576-87167c157a68.png)

**Comment by bruno-garcia** [comment]
CHanged shipped on 1.0.2
