### ISSUE TITLE
Can see only errors but no stacktrace - Unity WebGL

### ISSUE THREAD

**Issue by aliasifmoneyprep** [getsentry/sentry-unity-lite#9]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
 NET 1.2.0

### Steps to Reproduce

I integrated sentry SDK into my WebGL project. I can see the errors from my production release but i can not see the stack trace of these errors. 

In the dashboard i can see an error "exception.values.0.stacktrace.frames: Discarded invalid value ". Did i miss anything during during integration or there are some extra step needs to be taken to see the stack trace of the errors in the sentry.io dashboard 
 
### Expected Result

Stack trace missing and there is an error on dash board "exception.values.0.stacktrace.frames: Discarded invalid value "

### Actual Result

 Errors with no stack trace

**Comment by bruno-garcia** [comment]
Please follow this issue for WebGL support: https://github.com/getsentry/sentry-unity/issues/516
We plan to add support very soon
